language: node_js
node_js:
    - '14'
dist: focal
sudo: required
branches:
    only:
        - master
before_script:
    - npm install -g @angular/cli
script:
    - ng lint
    - ng build ngx-router-tweaks --prod
    - ng build demo --prod
